-- 1) Order fields
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS order_no bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS customer_name text NOT NULL DEFAULT 'غير محدد',
  ADD COLUMN IF NOT EXISTS product_name text NOT NULL DEFAULT 'غير محدد',
  ADD COLUMN IF NOT EXISTS call_status text NOT NULL DEFAULT 'not_called';

-- 2) Call attachments
ALTER TABLE public.calls
  ADD COLUMN IF NOT EXISTS recording_url text,
  ADD COLUMN IF NOT EXISTS screenshot_url text,
  ADD COLUMN IF NOT EXISTS outcome text,
  ADD COLUMN IF NOT EXISTS note text;

-- 3) Orders overview (list + stats)
CREATE OR REPLACE FUNCTION public.admin_orders_overview()
RETURNS jsonb
LANGUAGE plpgsql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $$
declare
  _items jsonb;
  _stats jsonb;
begin
  if not (public.has_role(auth.uid(),'admin') or public.has_perm(auth.uid(),'Orders.View')) then
    raise exception 'FORBIDDEN';
  end if;

  with base as (
    select o.id,
           o.order_no,
           o.customer_name,
           o.product_name,
           o.amount,
           o.status::text as status,
           o.call_status,
           o.handled,
           o.created_at,
           o.attempts_count,
           (now() > o.created_at + (o.target_response_minutes * interval '1 minute')
             and o.status in ('new','in_progress')) as is_late,
           s.name as seller_name,
           c.name as call_center_name,
           (select count(*) from public.calls cl where cl.order_id = o.id and cl.recording_url is not null) as recordings_count,
           (select count(*) from public.calls cl where cl.order_id = o.id and cl.screenshot_url is not null) as screenshots_count
    from public.orders o
    left join public.sellers s on s.id = o.seller_id
    left join public.call_centers c on c.id = o.call_center_id
  )
  select
    coalesce(jsonb_agg(to_jsonb(b) order by b.created_at desc), '[]'::jsonb),
    jsonb_build_object(
      'total', count(*),
      'new', count(*) filter (where status = 'new'),
      'in_progress', count(*) filter (where status = 'in_progress'),
      'confirmed', count(*) filter (where status = 'confirmed'),
      'rejected', count(*) filter (where status = 'rejected'),
      'unconfirmed', count(*) filter (where status <> 'confirmed'),
      'unhandled', count(*) filter (where handled = false),
      'late', count(*) filter (where is_late)
    )
  into _items, _stats
  from base b;

  return jsonb_build_object('items', _items, 'stats', _stats);
end;
$$;

-- 4) Order detail
CREATE OR REPLACE FUNCTION public.admin_order_detail(_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $$
declare result jsonb;
begin
  if not (public.has_role(auth.uid(),'admin') or public.has_perm(auth.uid(),'Orders.View')) then
    raise exception 'FORBIDDEN';
  end if;

  select jsonb_build_object(
    'order', (
      select jsonb_build_object(
        'id', o.id, 'order_no', o.order_no, 'customer_name', o.customer_name,
        'product_name', o.product_name, 'amount', o.amount, 'status', o.status::text,
        'call_status', o.call_status, 'handled', o.handled, 'attempts_count', o.attempts_count,
        'target_response_minutes', o.target_response_minutes,
        'first_attempt_at', o.first_attempt_at, 'closed_at', o.closed_at,
        'created_at', o.created_at, 'updated_at', o.updated_at,
        'seller_id', o.seller_id, 'seller_name', s.name,
        'call_center_id', o.call_center_id, 'call_center_name', c.name, 'call_center_code', c.code
      )
      from public.orders o
      left join public.sellers s on s.id = o.seller_id
      left join public.call_centers c on c.id = o.call_center_id
      where o.id = _id
    ),
    'calls', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', cl.id, 'started_at', cl.started_at, 'ended_at', cl.ended_at,
        'recording_url', cl.recording_url, 'screenshot_url', cl.screenshot_url,
        'outcome', cl.outcome, 'note', cl.note,
        'call_center_name', cc.name
      ) order by cl.started_at), '[]'::jsonb)
      from public.calls cl
      left join public.call_centers cc on cc.id = cl.call_center_id
      where cl.order_id = _id
    ),
    'complaints', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', cp.id, 'subject', cp.subject, 'status', cp.status::text, 'created_at', cp.created_at
      ) order by cp.created_at), '[]'::jsonb)
      from public.complaints cp where cp.order_id = _id
    )
  ) into result;

  return result;
end;
$$;